pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - check-success=CI / build (pull_request)
      - check-success=codecov/patch
    actions:
      merge:
        method: squash
      label:
        add: [dependency-update]
