pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [d10xa]
      label:
        add: [dependency-update]
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: squash
      label:
        add: [dependency-update]
