language: scala
scala:
  - 2.12.6
script: sbt clean coverage test
after_success: sbt coverageReport coveralls
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_deploy:
  - sbt universal:packageBin
  - export RELEASE_FILE=$(ls target/universal/jadd-*.zip)
deploy:
  provider: releases
  api_key:
    secure: hU6sFfkZMRkhx05txd0PTRu7tamZFN5gU+n7eeyjHBP/HMXxDXwYW3azef/4ZehTUes8juILAffiGiNvJCLQ17zP+TQHrTB76+EwKNf9t00GCzm3gns77OGDGGEzcOg+CcAqiDiQphCMP0FBubltMlqXe9KOiMhY2xubTq+w5ZB0aSVeFEswRSEqgpl6wWO2pDfYxe1wtpqsnFAj1tOhTNRWXB/ceqBHdOrspCGKPn1wpXIzp+VQ1UbDLE/6mBd1HsJR7bNhRW7IlBc3dh9S7WHTsqd4QmzhAbCbdGB2bikBxgB0n19lb6cpRLNBgRn2+wTtJFcz/8zBPlsF6PCNPXCurgO3bwHzg8h5VJNQ4sppemOLFvud1Fv3oeeph5bQBW3ypxy1uj6zDbTdNYC9l/D0HSb0+P0LFDX/+l5PFWxvxSW0GdACF+NNrRFXZNQiz3K1QWw7+/GdZUmiUnK1v9lVFsAP9IwxpMvJcL5Sccvg3qd2oJ5Uby9YfpXU9DzJJtC3lYvrdxDttdFsvWLvpWfukORWlBUzEvtnOVJEL2eyR5hmRVbhgXLX390TfqG3Vb4eLZLRojngSYGyiXoTTXMSsVA/oult0mbXfY9WXiTWSRY0AL31COo1NEOyIHJ9LPvpw7Wb8CnOYJ4NJOuTc/QENJWie2j0V9DldKOv5gY=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: gd1J91mkBKqRfc9+L9qRF2sJkwJ5ogQb+VcEIx33FgraJvP5mtbx+H1gOy829wusJBeMacl9YjPIpojoGIzqUvtsI+U2fTs/gnQH4PZ/TD6CPN6E/eV1Z9pDKrYQsSJ8N1px6OO1RUcha5tHOSBUvYCEnXOMenOL5BgbURNQNrxv5GTlolPvH0yHVjMm2DZD7DYXMLu0zND6nyLHGv5vwEFosufMNujzV+/gkGfHXj/yGke4HXv1GzzpecEm+OjBR+V7DdzA7/Yx0DqDaeBv4TU0P62zlTcUzkvDfdDb7VeIbGYT3FNxZDSAE7CdZk5/9idblvUcSjI15TfXDWXpaURYJfizXz7yaBXJn4/UaUtPeM3QJUyNRgmIlxTKpwo8wWzwiMFv0Ww9cEzKScG6XRkXEZWGPOWcOnGQd6Zx9PJq1B4h3ek99+B4grfWdWOLxr8wCg09o4/LjoADaj0yOPETyylAjXtK+pXqJCfhb3CveevW2WcqGPBhcuHC8tn/bE7FJDSxjF1T+YhMX4ZLXA72R5zlP2ooiQkUokZk0RHXyLn+1UqeTESIpyiI7IoRnGc/43S7vQwMDSRRtl4WW19PrCXscPuaer6HX9SrC/zccUIc61kkOaiM+ILepH4zACGcunnvIX/DNJ9n7xRX/hbaDNltJf3wtyskEla3WxM=
