name: publish
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Build
        run: sbt compile
      - name: Import GPG
        env:
          GPG_PRIVATE_KEY: "${{ secrets.GPG_PRIVATE_KEY }}"
        run: |
          echo $GPG_PRIVATE_KEY | base64 -d | gpg --batch --import
      - name: Publish
        env:
          GPG_KEYID: "${{ secrets.GPG_KEYID }}"
          PGP_PASSPHRASE: "${{ secrets.PGP_PASSPHRASE }}"
        run: sbt publishSigned sonatypeRelease
      - name: Delete keys
        env:
          GPG_KEYID: "${{ secrets.GPG_KEYID }}"
        run: |
          gpg --batch --yes --delete-secret-keys $GPG_KEYID
          gpg --batch --yes --delete-keys $GPG_KEYID
